require:
  - rubocop-rspec
# Explanations of all possible options:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

# TODO: enable this when Ruby 3.0 is out.
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/NumericPredicate:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/HeredocIndentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/RescuedExceptionsVariableName:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/FilePath:
  Enabled: true
  IgnoreMethods: true
  Exclude:
    - "spec/cirro_io_v2/**/*_spec.rb"


Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 12

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
